// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hUMWEvlvHtjzv5DGJ6BS8-q5uYAg9NE',
    appId: '1:494935881953:web:3d28ed4fdd7558577e1fa0',
    messagingSenderId: '494935881953',
    projectId: 'mobilelogin-64ea1',
    authDomain: 'mobilelogin-64ea1.firebaseapp.com',
    storageBucket: 'mobilelogin-64ea1.appspot.com',
    measurementId: 'G-P8R1G1ZB39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRpKGWI-u2EA1j_VbPxkrWC47gK8qMx0',
    appId: '1:494935881953:android:d954983e91d6d3487e1fa0',
    messagingSenderId: '494935881953',
    projectId: 'mobilelogin-64ea1',
    storageBucket: 'mobilelogin-64ea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVCgdHrsoNWM6sDRePUUwwmTHsDWCuBv4',
    appId: '1:494935881953:ios:fec6cca3e604d9857e1fa0',
    messagingSenderId: '494935881953',
    projectId: 'mobilelogin-64ea1',
    storageBucket: 'mobilelogin-64ea1.appspot.com',
    iosClientId:
        '494935881953-0gk6acd1juf1pfobbenpapq5ndrsvp1t.apps.googleusercontent.com',
    iosBundleId: 'com.srinivasan.whatsappUi',
  );
}
